log: debug
server:
  http:
    enabled: true
    address: 127.0.0.1:8080
  https:
    enabled: true
    address: 127.0.0.1:8443
    cert: cert.example.pem
    key: key.example.pem

auth:
  enabled: true
  filename: users.example.plaintext

monitoring:
  enabled: true
  address: 127.0.0.1:8088

app_endpoint:
  timeout: 10s

mower_endpoint:
  read_buffer_size: 1024
  write_buffer_size: 1024
  tunnel:
    ping_interval: 1m
    ping_timeout: 10s
    pong_timeout: 10s
