# https://jeremievallee.com/2018/05/28/kubernetes-rbac-namespace-user.html
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ardumower-ci
  namespace: ardumower

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ardumower-ci-full-access
  namespace: ardumower
rules:
- apiGroups: ["", "extensions", "apps", "networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ardumower-ci-view
  namespace: ardumower
subjects:
- kind: ServiceAccount
  name: ardumower-ci
  namespace: ardumower
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ardumower-ci-full-access
